name: Bug Report
description: Report a bug in this project
title: "[Bug]: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug!
  - type: input
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: How can we reproduce the bug?
      placeholder: 1. Go to '...'
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS, browser, version, etc.