name: Deploy website
on:
  push:
    branches:
      - main
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Install dependencies
              run: npm ci
            - name: Run linting
              run: npm run lint
            - name: Run tests
              run: npm run test
    build:
        runs-on: ubuntu-latest
        needs: test
        outputs:
            js-script-file: ${{ steps.jsscript.outputs.js-script-file }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Install dependencies
              run: npm ci
            - name: Build project
              run: npm run build
            - name: Set output for JS script file
              id: jsscript
              run: find dist/assets/*.js -type f -execdir echo "js-script-file={}"  >> $GITHUB_OUTPUT \;
            - name: Archive build artifacts
              uses: actions/upload-artifact@v4
              with:
                name: build-artifacts
                path: dist
    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Get build artifacts
              uses: actions/download-artifact@v4
              with:
                name: build-artifacts
                path: dist
            - name: echo the build output js script file name
              run: echo "JS script file: ${{ needs.build.outputs.js-script-file }}"
            - name: List current directory to see the that the artifacts are present
              run: ls -laR
            - name: Deploy
              run: echo "Deploying to production server..." # Replace with actual deployment command