name: Deploy website
on:
  push:
    branches:
      - main
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Install dependencies
              run: npm ci
            - name: Run linting
              run: npm run lint
            - name: Run tests
              run: npm run test
    build:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Install dependencies
              run: npm ci
            - name: Build project
              run: npm run build
            - name: Archive build artifacts
              uses: actions/upload-artifact@v3
              with:
                name: build-artifacts
                path: |
                    dist
                    package.json #this isn't really needed but used as example of multiple paths/files
    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Deploy
              run: echo "Deploying to production server..." # Replace with actual deployment command