name: Pull Request Workflow
on:
  pull_request:
  workflow_dispatch:
jobs:
    test-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Install dependencies
              run: npm ci
            - name: Run linting
              run: npm run lint
            - name: Run tests
              run: npm test