name: Test and Deploy Project
on:
    push:
        branches:
        - main
    workflow_dispatch:
jobs:
    test-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Install dependencies
              run: npm ci
            - name: Run linting
              run: npm run lint
            - name: Run tests
              run: npm test
            - name: Build project
              run: npm run build
            - name: Deploy to production server
              run: echo "Deploying to production server..." # Replace with actual deployment command